### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by ethanl21** [ethanl21/musaic-fxend#3]
# User Story

As a user of our website, I want to log in to my account so that I may access information that is specific to me.

# Tasks

- [x] Login form/card React component design + implementation
- [x] Supabase Auth email login
- [x] Supabase Auth social login (Google, GitHub, Discord)
- [x] Account creation (email)
- [x] Allow logged in users to log out of their account
- [x] Visually indicate if the user is logged in or not

# Definition of Done

- A user of our website can create an account or login using an email address and password or third-party social account.
- Logged in users can log out
- Logged in users can see information specific to their account
- Users can only see information specific to an account if they are logged in to that account

**Comment by ethanl21** [comment]
I set up our Supabase project to use Twilio SendGrid to send verification emails 👍

**Comment by ethanl21** [comment]
I switched from SendGrid to Resend since it seems simpler. Also, I enabled log in with Spotify since we're going to need that anyways.
