### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by ethanl21** [ethanl21/musaic-fxend#5]
# User Story

As a visitor to our project's website, I want to see a homepage so that I know why our project exists.

# Tasks

- [x] Design home page using the shadcn/ui components
- [x] Create a [Next.js](https://nextjs.org/docs) page based. We're using the **app** router.

## Notes

- To create a Next.js page, create a `page.tsx` at the desired path in the `app` folder.
  - For example, to create the page `<website url>/one/two`, create `app/one/two/page.tsx`.
  - To create the root page, create `app/page.tsx`.

# Definition of Done

- [x] Our website's root URL returns an attractive website
- [x] Our website's main features are displayed prominently on the home page
- [x] Links to the sign up/log in page (can be placeholder) are easy to find

# Notes

- We're using [shadcn/ui](https://ui.shadcn.com/docs) for our React components
- We're using [Tailwind CSS](https://tailwindcss.com/docs/installation) to style our web pages
